// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/messages": {
            "post": {
                "description": "Add a new message to the queue for sending",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Create a new message",
                "parameters": [
                    {
                        "description": "Message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.MessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/apidocs.MessageCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidocs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidocs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/messages/sent": {
            "get": {
                "description": "Retrieve a paginated list of sent messages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Get sent messages",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apidocs.MessagesListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidocs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidocs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/scheduler/start": {
            "post": {
                "description": "Start automatic message sending process",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scheduler"
                ],
                "summary": "Start the message scheduler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apidocs.SchedulerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidocs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidocs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/scheduler/status": {
            "get": {
                "description": "Get current status of the message scheduler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scheduler"
                ],
                "summary": "Get scheduler status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apidocs.SchedulerResponse"
                        }
                    }
                }
            }
        },
        "/v1/scheduler/stop": {
            "post": {
                "description": "Stop automatic message sending process",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scheduler"
                ],
                "summary": "Stop the message scheduler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apidocs.SchedulerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidocs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidocs.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apidocs.ErrorData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "details": {
                    "type": "string",
                    "example": "Invalid request parameters"
                }
            }
        },
        "apidocs.ErrorResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/apidocs.ErrorData"
                },
                "msg": {
                    "type": "string",
                    "example": "Validation failed"
                },
                "status": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "apidocs.MessageCreatedResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/apidocs.MessageData"
                },
                "msg": {
                    "type": "string",
                    "example": "Message created successfully"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "apidocs.MessageData": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Insider - Project"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "failure_reason": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "message_id": {
                    "type": "string",
                    "example": "msg_123456"
                },
                "sent_at": {
                    "type": "string",
                    "example": "2024-01-15T10:35:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "to": {
                    "type": "string",
                    "example": "+905551111111"
                }
            }
        },
        "apidocs.MessagesListData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apidocs.MessageData"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/pagination.PaginationInfo"
                }
            }
        },
        "apidocs.MessagesListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/apidocs.MessagesListData"
                },
                "msg": {
                    "type": "string",
                    "example": "Request processed successfully"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "apidocs.SchedulerData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Scheduler started successfully"
                },
                "status": {
                    "type": "string",
                    "example": "running"
                }
            }
        },
        "apidocs.SchedulerResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/apidocs.SchedulerData"
                },
                "msg": {
                    "type": "string",
                    "example": "Scheduler started successfully"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "domain.MessageRequest": {
            "type": "object",
            "required": [
                "content",
                "to"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 160,
                    "example": "Insider - Project"
                },
                "to": {
                    "type": "string",
                    "example": "+905551111111"
                }
            }
        },
        "pagination.PaginationInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Insider Message System API",
	Description:      "Automatic message sending system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
